apiVersion: apps/v1
kind: Deployment
metadata:
  name: profiler-deployment
  labels:
    app: profiler-demo-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: profiler-demo-python
  template:
    metadata:
      labels:
        app: profiler-demo-python
    spec:
      volumes:
      - name: stackdriver-profiler
        secret:
          secretName: stackdriver-profiler
      containers:
      - name: profiler-demo-python
        image: gcr.io/csp-testing/profiler-demo-python:latest
        volumeMounts:
        - name: stackdriver-profiler
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/stackdriver-profiler.json
        ports:
        - containerPort: 8080
